import Queue.CommandQueue as CommandQueue

priority_queue = CommandQueue.PriorityQueue()
priority_queue.enqueue({"priority": 3, "command": "hello"})
priority_queue.enqueue({"priority": 7, "command": "hi"})
priority_queue.enqueue({"priority": 5, "command": "bonjour"})
priority_queue.enqueue({"priority": 9, "command": "nice to meet you"})
priority_queue.enqueue({"priority": 1, "command": "yokoso"})
priority_queue.enqueue({"priority": 4, "command": "glad to see you"})
priority_queue.poll()
priority_queue.enqueue({"priority": 8, "command": "introduce myself"})
priority_queue.poll()
priority_queue.poll()
priority_queue.enqueue({"priority": 6, "command": "let me know"})
priority_queue.dequeue("yokoso")
priority_queue.poll()
priority_queue.dequeue("glad to see you")
peek = priority_queue.peek()
print(peek)
priority_queue.poll()
priority_queue.poll()
priority_queue.enqueue({"priority": 2, "command": "please call me"})
priority_queue.poll()
priority_queue.poll()
priority_queue.poll()

print()
for process in priority_queue.result:
    print(process)
print()
